### ISSUE TITLE
%SIM-ERROR: MT1: Can't enable write when attached read only

### ISSUE THREAD

**Issue by marcosadsjunior** [pkimpel/retro-b5500#55]
Hello All,

Guys I'm completely new in this OS, in my work people start a project to internalize the Unisys MCP systems and is completely different from everything I ever tryed haha.

As doesn't have MCP Express anymore I trying to find anything I can run and trainning to understanding better the OS.

I'm trying to build from source the system but I froze in some parte that I can't understand. The erro is about some file that is read-only but I can't find it. Anyone knows how to sove it. I really apreciate your help.

`R  CRA REL CARD 1:XREF/JONES= 2
R #XREF/JONES= 2: DOCUMENT FOUND
R  XREF/JONES= 2 EOJ 1034
R  5:LIBMAIN/DISK= 2 BOJ 1034
R .FLOWCHT/DISK NOT DUMPED(NOT ON DISK)
R #MT RQD EXTRAS FILE000/mnt/c/Users/msmar/projetos/simh/BIN/xiii_build.ini-63> set mt1 writeenable
%SIM-ERROR: MT1: Can't enable write when attached read only
/mnt/c/Users/msmar/projetos/simh/BIN/xiii_build.ini-63> at mt1 -n -f p7b extras.bin
%SIM-INFO: MT1: creating new file: extras.bin
%SIM-INFO: MT1: Tape Image 'extras.bin' scanned as P7B format
 1:LIBMAIN/DISK= 2
R  PBD/0118001 REMOVED
R  PRNPBT/DISK= 1 EOJ 1034
R  0:PRNPBT/DISK= 1 BOJ 1034
R  PBD/0122001 REMOVED
R  PRNPBT/DISK= 1 EOJ 1034
R  0:PRNPBT/DISK= 1 BOJ 1034
R  PBD/0123001 REMOVED
R  PRNPBT/DISK= 1 EOJ 1034
R  0:PRNPBT/DISK= 1 BOJ 1034
R  PBD/0124001 REMOVED
R  PRNPBT/DISK= 1 EOJ 1034
R  0:PRNPBT/DISK= 1 BOJ 1034
R  PBD/0125001 REMOVED
R  PRNPBT/DISK= 1 EOJ 1034
R  0:PRNPBT/DISK= 1 BOJ 1034
R  PBD/0126001 REMOVED
R  PRNPBT/DISK= 1 EOJ 1034
R #MTB TAPE MK, RW/L
I PGMTB
R  MTB WRITE LOCK
R`

**Comment by marcosadsjunior** [comment]
the file extras.bin that is created is with all permitions but empty... 

`
root@BOOK-HB5BSI4ADS:/mnt/c/Users/msmar/projetos/simh/BIN# ls -lh
total 158M
-rwxrwxrwx 1 root root  14M Aug 24 09:59 B5500-XIII-SYMBOL1-adc00255.bcd
-rwxrwxrwx 1 root root  13M Aug 24 09:59 B5500-XIII-SYMBOL2-adc00253.bcd
-rwxrwxrwx 1 root root  13M Mar 12  2013 B5500-XIII-SYSTEM-adc00257.bcd
-rwxrwxrwx 1 root root  12M Aug 24 09:57 CUBEA13.BCD
-rwxrwxrwx 1 root root  11M Aug 24 09:57 CUBEB13.bcd
-rwxrwxrwx 1 root root 2.8M Aug 24 09:57 CUBE_LBR-CORR.bcd
-rwxrwxrwx 1 root root 1.5K Aug 24 09:57 README.txt
-rwxrwxrwx 1 root root 953K Aug 24 09:09 b5500
-rwxrwxrwx 1 root root  37K Aug 24 09:57 build1.job
-rwxrwxrwx 1 root root 1.6K Aug 24 09:57 build2.job
drwxrwxrwx 1 root root 4.0K Aug 24 09:08 buildtools
-rwxrwxrwx 1 root root  19K Aug 24 09:57 cold.card
-rwxrwxrwx 1 root root 198K Aug 24 09:57 extra.job
-rwxrwxrwx 1 root root    0 Aug 25 15:33 extras.bin
-rwxrwxrwx 1 root root  14K Aug 24 09:57 load.job
-rwxrwxrwx 1 root root  66K Aug 25 14:28 punch.dck
-rwxrwxrwx 1 root root  16K Aug 24 09:57 set_test.job
-rwxrwxrwx 1 root root 243K Aug 24 09:57 stress.job
-rwxrwxrwx 1 root root 1.1K Aug 24 09:57 tss_setup.job
-rwxrwxrwx 1 root root  40M Aug 25 14:57 xiii.lst
-rwxrwxrwx 1 root root 8.0M Aug 25 21:15 xiii0.dsk
-rwxrwxrwx 1 root root  46M Aug 25 14:57 xiii1.dsk
-rwxrwxrwx 1 root root 3.5K Aug 24 09:57 xiii_build.ini
-rwxrwxrwx 1 root root  787 Aug 24 09:57 xiii_load.ini
-rwxrwxrwx 1 root root  341 Aug 24 09:57 xiii_run.ini
-rwxrwxrwx 1 root root 6.2K Aug 24 09:57 xiii_test.ini
-rwxrwxrwx 1 root root  292 Aug 24 09:57 xiii_tss.ini
`

**Comment by pkimpel** [comment]
I'm sorry, but I cannot help you with problems related to the SIMH 
emulator for the B5500. The retro-b5500 emulator is written in 
JavaScript and runs in a standard web browser. For the SIMH-based 
emulator, I suggest you contact Richard Cornwell at ***@***.***

That said, I think you're wasting your time trying to learn about the 
modern Unisys MCP from a B5500 emulator and operating system. The B5500 
was a system used in the 1960s and early 1970s, and the versions of that 
MCP operating system available to us are more than 50 years old. The 
B5500 was a forerunner of the modern Unisys MCP systems, and there are 
some similarities in the architecture, but nothing you learn about the 
B5500 will be useful for the modern MCP.

Paul Kimpel


------------------------------------------------------------------------

*Subject:* [pkimpel/retro-b5500] %SIM-ERROR: MT1: Can't enable write 
when attached read only (Issue #55)
*Date:* Sunday, August 25, 2024 at 4:31 PM
*From:* Marcos Antonio da Silva Junior ***@***.***>
*To:* pkimpel/retro-b5500 ***@***.***>
*Cc:* Subscribed ***@***.***>

> Hello All,
>
> Guys I'm completely new in this OS, in my work people start a project to internalize the Unisys MCP systems and is completely different from everything I ever tryed haha.
>
> As doesn't have MCP Express anymore I trying to find anything I can run and trainning to understanding better the OS.
>
> I'm trying to build from source the system but I froze in some parte that I can't understand. The erro is about some file that is read-only but I can't find it. Anyone knows how to sove it. I really apreciate your help.
>
> `R  CRA REL CARD 1:XREF/JONES= 2
> R #XREF/JONES= 2: DOCUMENT FOUND
> R  XREF/JONES= 2 EOJ 1034
> R  5:LIBMAIN/DISK= 2 BOJ 1034
> R .FLOWCHT/DISK NOT DUMPED(NOT ON DISK)
> R #MT RQD EXTRAS FILE000/mnt/c/Users/msmar/projetos/simh/BIN/xiii_build.ini-63> set mt1 writeenable
> %SIM-ERROR: MT1: Can't enable write when attached read only
> /mnt/c/Users/msmar/projetos/simh/BIN/xiii_build.ini-63> at mt1 -n -f p7b extras.bin
> %SIM-INFO: MT1: creating new file: extras.bin
> %SIM-INFO: MT1: Tape Image 'extras.bin' scanned as P7B format
>   1:LIBMAIN/DISK= 2
> R  PBD/0118001 REMOVED
> R  PRNPBT/DISK= 1 EOJ 1034
> R  0:PRNPBT/DISK= 1 BOJ 1034
> R  PBD/0122001 REMOVED
> R  PRNPBT/DISK= 1 EOJ 1034
> R  0:PRNPBT/DISK= 1 BOJ 1034
> R  PBD/0123001 REMOVED
> R  PRNPBT/DISK= 1 EOJ 1034
> R  0:PRNPBT/DISK= 1 BOJ 1034
> R  PBD/0124001 REMOVED
> R  PRNPBT/DISK= 1 EOJ 1034
> R  0:PRNPBT/DISK= 1 BOJ 1034
> R  PBD/0125001 REMOVED
> R  PRNPBT/DISK= 1 EOJ 1034
> R  0:PRNPBT/DISK= 1 BOJ 1034
> R  PBD/0126001 REMOVED
> R  PRNPBT/DISK= 1 EOJ 1034
> R #MTB TAPE MK, RW/L
> I PGMTB
> R  MTB WRITE LOCK
> R`
>
>

**Comment by pkimpel** [comment]
Closed as not applicable to retro-b5500.
